### ISSUE TITLE
Postsubmit job failed to push image

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/ibm-powervs-block-csi-driver#134]
/kind bug

**What happened?**

Postsubmit job failed, more Information: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-ibm-powervs-block-csi-driver-push-images/1498960118182580224

**What you expected to happen?**

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Comment by Madhan-SWE** [comment]
Image push issues were solved and the image are pushed successfully to gcr on every post submit job.
