### ISSUE TITLE
Explore and remove code for filesystem volume (if not appropriate)

### ISSUE THREAD

**Issue by Madhan-SWE** [kubernetes-sigs/ibm-powervs-block-csi-driver#165]
/kind bug

**What happened?**
There is code for both block and filesystem volumes in the powervs csi driver.
Explore about both block and file system volumes.
Remove the code for file system volumes if it is not appropriate.

**What you expected to happen?**
Volumes created by PowerVS CSI Driver are expected to be block volumes.

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Comment by Madhan-SWE** [comment]
The objective of IBM PowerVS Block CSI Driver is to enable workloads to make use of block devices created in Power VS.
There is no file system disks can be created in the PowerVS.
But still we could see code for File system volumes: https://github.com/kubernetes-sigs/ibm-powervs-block-csi-driver/blob/18af96f9f253078318ca0378bc10db4e022a0dfc/pkg/driver/node.go#L350

Which is not actually needed. I think we can cleanup the file system related code.
@mkumatag what is your thoughts on this?

**Comment by mkumatag** [comment]
and who will advertise the capabilities here https://github.com/kubernetes-sigs/ibm-powervs-block-csi-driver/blob/4cb7aae9e69ae34a8a1059b39e424684dc8d5807/pkg/driver/node.go#L330 and hope this will never return non-block stuff

**Comment by Madhan-SWE** [comment]
@mkumatag,
I have explored about modes for PVCs. 

```
volumeMode is an optional API parameter. Filesystem is the default mode used when volumeMode parameter is omitted.

A volume with volumeMode: Filesystem is mounted into Pods into a directory. If the volume is backed by a block device and the device is empty, Kubernetes creates a filesystem on the device before mounting it for the first time.

You can set the value of volumeMode to Block to use a volume as a raw block device. Such volume is presented into a Pod as a block device, without any filesystem on it. This mode is useful to provide a Pod the fastest possible way to access a volume, without any filesystem layer between the Pod and the volume. On the other hand, the application running in the Pod must know how to handle a raw block device.
```

reference: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#volume-mode

Currently we are allowing the pod to mount the power vs volume in either block mode or filesystem mode. Eventhough the Eventhough the PowerVS volumes are block volumes, volume mode represents how we want that volume to be mounted to the Pod. So, the filesystem related code in our driver represents the volume mode of the PVC.


The conclusion is `There is no code refactor needed, current code does the job as expected`.
