### ISSUE TITLE
Standardize image name for PowerVS CSI Driver deployment

### ISSUE THREAD

**Issue by Madhan-SWE** [kubernetes-sigs/ibm-powervs-block-csi-driver#181]
**Is your feature request related to a problem?/Why is this needed**
Currently we are using `main` image as a stable version. Which will always pull the latest code and deploy it in the cluster.
Explore standard ways to deploy drivers of particular version.

/feature

**Comment by Madhan-SWE** [comment]
EBS and EFS CSI drivers hard code the version of the driver in the yaml files.
for example, 
- if we clone EBS driver from `1.0.0` branch, then the deployment file will have image tag as `1.0.0`
-  if we clone EBS driver from `2.0.0` branch, then the deployment file will have image tag as `2.0.0`
User can simply clone the driver of their expected version and then they can deploy the stable folder.

Ref: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/da9873c6bd23ac350f61441a95c8f2aa6b241683/deploy/kubernetes/overlays/stable/gcr/kustomization.yaml#L7
```
git clone repo -b version_one
kubectl apply -k deploy/stable
```


Azure drivers follows a different way. They have separate folders for each and every version of the driver.
They also have script to install a particular version.
For example if we want to install driver of version 1.0.0,
```
./install_driver.sh 1.0.0
```
This will go and apply yaml files in the folder `kubectl apply -k deploy/stable/1.0.0`.

Ref: https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy

**Comment by mkumatag** [comment]
Rather the issue we are trying to solve is the deployment model, how the end user is going to deploy the driver. I see 2 options
1. Helm chart
**Pro:**
- only one single command to deploy which will decide what to fetch where to fetch and install
- Easy to override the values if any like image name, api key etc..
**Cons:**
- Need to depend on another external tool(helm)
- Need to host the helm chart somewhere
2. Use the specs from the release artefacts
**Pro:**
- Easy to ship, for every release with minimum effort, specs can be shipped in the release artefacts
Cons:

It will be good to have both the options available for the user, that way user can select any either way they want to publish the artefacts.

@Madhan-SWE add to the list with other options we have.

**Comment by Madhan-SWE** [comment]
> Rather the issue we are trying to solve is the deployment model, how the end user is going to deploy the driver. I see 2 options
> 
> 1. Helm chart
>    **Pro:**
> 
> * only one single command to deploy which will decide what to fetch where to fetch and install
> * Easy to override the values if any like image name, api key etc..
>   **Cons:**
> * Need to depend on another external tool(helm)
> * Need to host the helm chart somewhere
> 
> 2. Use the specs from the release artefacts
>    **Pro:**
> 
> * Easy to ship, for every release with minimum effort, specs can be shipped in the release artefacts
>   Cons:
> 
> It will be good to have both the options available for the user, that way user can select any either way they want to publish the artefacts.
> 
> @Madhan-SWE add to the list with other options we have.


Currently the method 2 is used to deploy the driver.
Opened a separate issue for adding helm chart mode of deployment for the `ibm-powervs-block-csi-driver`, issue: https://github.com/kubernetes-sigs/ibm-powervs-block-csi-driver/issues/97

**Comment by Madhan-SWE** [comment]
Hence the issue can be closed.
