### ISSUE TITLE
Add additional features in Makefile, add hack script(util)

### ISSUE THREAD

**Issue by Madhan-SWE** [kubernetes-sigs/ibm-powervs-block-csi-driver#20]
Add below additional features in the make file:

- [x] gofmt
- [x] govet
- [x] golangci-lint
- [x] Mockgen
- [x] verify vendor
- [ ] test e2e tests
- [x] tests

Add required shell scripts utilities for the above features.

**Comment by Madhan-SWE** [comment]
Changes are available in the private branch **feature_remove_pvm_instance_id_v3**.

**Comment by Madhan-SWE** [comment]
E2e tests integration to ci is pending as the platform creation with `clusterctl` was failing.
Need to revisit `clusterctl`.

**Comment by yussufsh** [comment]
/close
We will handle e2e task in #446
