### ISSUE TITLE
Use centos stream image for examples

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/ibm-powervs-block-csi-driver#262]
/kind bug

**What happened?**

old centos image is used for the example which needs to be changed to centos stream image.

newer image: `quay.io/centos/centos:stream8`

https://github.com/kubernetes-sigs/ibm-powervs-block-csi-driver/blob/305da5b68961a32ff0a4239d5fc058c2694a3c5f/examples/kubernetes/storageclass/specs/example.yaml#L30

**What you expected to happen?**

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Comment by Madhan-SWE** [comment]
We've decided to use busy box image over centos recently.
Can we use busybox image in all the examples?

**Comment by mkumatag** [comment]
> @mkumatag, We've decided to use busy box image over centos recently.
> Can we use busybox image in all the examples?

I'm fine if it is serving the purpose, only reason to use centos like image is to install any tool on top for testing or debugging.
