### ISSUE TITLE
Create prow jobs for release-* branches

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/ibm-powervs-block-csi-driver#285]
/kind cleanup

Currently we have prow jobs only for the [main branch](https://github.com/kubernetes/test-infra/blob/8039a827978835b6cc57fcd7b4bbfa3bd35c6d05/config/jobs/image-pushing/k8s-staging-cloud-provider-ibm.yaml), lets have prow jobs for the `release-*` branches as well.

**Comment by Madhan-SWE** [comment]
Prow jobs are already configured for the release branch here: https://github.com/kubernetes/test-infra/blob/8039a827978835b6cc57fcd7b4bbfa3bd35c6d05/config/jobs/image-pushing/k8s-staging-cloud-provider-ibm.yaml

Test PR: https://github.com/kubernetes-sigs/ibm-powervs-block-csi-driver/pull/293

**Comment by mkumatag** [comment]
> Prow jobs are already configured for the release branch here: https://github.com/kubernetes/test-infra/blob/8039a827978835b6cc57fcd7b4bbfa3bd35c6d05/config/jobs/image-pushing/k8s-staging-cloud-provider-ibm.yaml
> 
> Test PR: #293

oops, I mentioned the wrong links there, here is the right link - https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/ibm-powervs-block-csi-driver/ibm-powervs-block-csi-driver.yaml
- Rightnow it is using the gcr.io/k8s-staging-test-infra/kubekins-e2e:v20221107-33c989e684-master which needs to be modified to the released k8s version which branch is using.
- golang needs to be updated to 1.19 [here](https://github.com/kubernetes/test-infra/blob/9ccfc428ea750366c766d7cfcf1f13b73e3f83bc/config/jobs/kubernetes-sigs/ibm-powervs-block-csi-driver/ibm-powervs-block-csi-driver.yaml#L55)

**Comment by Madhan-SWE** [comment]
- These [jobs](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/ibm-powervs-block-csi-driver/ibm-powervs-block-csi-driver.yaml) are applicable to all the branches in the repository.
- This image `gcr.io/k8s-staging-test-infra/kubekins-e2e:v20221107-33c989e684-master ` will be periodically updated by the bot and this particular image was updated yesterday
- Created PR to update the Golang version: https://github.com/kubernetes/test-infra/pull/27923

**Comment by mkumatag** [comment]
> * These [jobs](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/ibm-powervs-block-csi-driver/ibm-powervs-block-csi-driver.yaml) are applicable to all the branches in the repository (There is an option to skip branches, but currently we are not using)
> * This image `gcr.io/k8s-staging-test-infra/kubekins-e2e:v20221107-33c989e684-master` will be periodically updated by the bot and this particular image was updated yesterday
> * Created PR to update the Golang version: [Update golang to 1.19 kubernetes/test-infra#27923](https://github.com/kubernetes/test-infra/pull/27923)

But there are other tags for older releases like 1.25, 1.24 etc.. we should have the same version mapped for the released branches and not the master one.

<img width="571" alt="image" src="https://user-images.githubusercontent.com/12646029/200562763-f94549f6-af8f-45fd-9da3-b00a863eecd3.png">

**Comment by Madhan-SWE** [comment]
Prow job added for the release branches: https://github.com/kubernetes/test-infra/pull/27942

**Comment by Madhan-SWE** [comment]
closing this as the prow jobs are added.
