### ISSUE TITLE
Upgrade go version 1.22

### ISSUE THREAD

**Issue by yussufsh** [kubernetes-sigs/ibm-powervs-block-csi-driver#671]
**Is your feature request related to a problem?/Why is this needed**

/feature

**Describe the solution you'd like in detail**

**Describe alternatives you've considered**

**Additional context**

**Comment by yussufsh** [comment]
/assign @kishen-v 
Please update the go version for this project, you also need to make changes in the job configurations. Thanks.

**Comment by kishen-v** [comment]
Hi @yussufsh,
I've made the required changes to update the go version to 1.21 to 1.22, the build actions will use 1.22, based on the version in the go.mod file.

Related PR for test-infra:
https://github.com/kubernetes/test-infra/pull/32661
