### ISSUE TITLE
CSI driver can't read credentials from file

### ISSUE THREAD

**Issue by bertinatto** [kubernetes-sigs/ibm-powervs-block-csi-driver#727]
The [CIS Kubernetes Benchmark](https://www.cisecurity.org/benchmark/kubernetes) recommends using secrets as files rather than environment variables. Currently, the only supported method for passing credentials to the CSI driver is via the `IBMCLOUD_API_KEY` environment variable.

To ensure compliance with the CIS Benchmark and to avoid being flagged by automated tools such as the OpenShift Compliance Operator, the CSI driver should also support reading credentials from a file.

**Comment by kishen-v** [comment]
cc @GunaKKIBM.

**Comment by GunaKKIBM** [comment]
Raised a PR for this - https://github.com/kubernetes-sigs/ibm-powervs-block-csi-driver/pull/746 

Note: As of now, this PR is only meant for reading credentials from file, rather than getting it from ENV.
With this approach(or even if it is reading from env), the disadvantage is that, whenever there is an apikey update, the controller/node server pod needs to be restarted to pick up the new apikey. Changes to make it dynamic can be done by means of a watcher, or may be reading apikey for every call to IAAS. 

@yussufsh , please share your thoughts.

**Comment by GunaKKIBM** [comment]
Sharing test results with changes in https://github.com/kubernetes-sigs/ibm-powervs-block-csi-driver/pull/746

Test case 1:  Secret mounted into container and API_KEY_PATH is specified
```
% kubectl apply -f specs 
persistentvolumeclaim/powervs-claim created
pod/app created
storageclass.storage.k8s.io/powervs-sc created
% kubectl get pvc
NAME            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
powervs-claim   Bound    pvc-d1b41101-aad5-49ad-bb17-4e7287f4967b   4Gi        RWO            powervs-sc     <unset>                 50s
% kubectl get pods
NAME   READY   STATUS              RESTARTS   AGE
app    0/1     ContainerCreating   0          53s
% kubectl get pods
NAME   READY   STATUS    RESTARTS   AGE
app    1/1     Running   0          103s
```

Test case 2: API_KEY_PATH is specified but secret is not mounted (controller server fails)
Error seen in logs
```
F0924 07:57:55.132313       1 controller.go:134] Failed to get powervs cloud: error reading apikey: open /etc/secrets/IBMCLOUD_API_KEY: no such file or directory
```

Test case 3: API_KEY is specified as only env (secret is not mounted into the container)
```
W0924 08:05:46.831037       1 powervs.go:281] API_KEY_PATH is undefined
I0924 08:05:46.831044       1 powervs.go:269] Falling back to read IBMCLOUD_API_KEY environment variable for the key

% kubectl apply -f specs 
persistentvolumeclaim/powervs-claim created
pod/app created
storageclass.storage.k8s.io/powervs-sc unchanged

% kubectl get pods
NAME   READY   STATUS    RESTARTS   AGE
app    1/1     Running   0          2m40s
% kubectl get pvc 
NAME            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
powervs-claim   Bound    pvc-4734800e-0af4-479d-ba5f-ff28aa45599f   4Gi        RWO            powervs-sc     <unset>                 2m48s
```

**Comment by yussufsh** [comment]
This is completed.
