### ISSUE TITLE
Use errors.New instead of fmt.Errorf

### ISSUE THREAD

**Issue by GunaKKIBM** [kubernetes-sigs/ibm-powervs-block-csi-driver#755]
To frame errors it is better to use errors.New instead of fmt.Errorf 

Here's a comment in one of the PRs for reference: https://github.com/kubernetes-sigs/ibm-powervs-block-csi-driver/pull/746#discussion_r1768706207

**Comment by irapandey** [comment]
@GunaKKIBM  - Can I take this up if you haven't tstarted? Would give time to look around the codebase as well :)

**Comment by GunaKKIBM** [comment]
Sure @irapandey. You may assign it to yourself
